# https://golangci-lint.run/usage/configuration/#config-file
linters:
  disable-all: true
  enable:
    - goerr113
    - errcheck
    - goimports
    # - paralleltest # missing the call to method parallel, but testify does not seem to work well with parallel test: https://github.com/stretchr/testify/issues/187
    - revive # revive supersedes golint, which is now archived
    - staticcheck
    - vet
    - forbidigo
run:
  skip-dirs:
    - ^api
    - ^proto
    - ^.git
linters-settings:
  govet:
    fieldalignment: 0
  revive:
    severity: error
    confidence: 0.8
    enable-all-rules: true
    rules:
      # Rule tuning
      - name: cognitive-complexity
        arguments:
          - 25
      - name: cyclomatic
        arguments:
          - 25
      - name: function-result-limit
        arguments:
          - 5
      - name: unhandled-error
        arguments:
          - "fmt.*"
          - "bytes.Buffer.*"
          - "strings.Builder.*"
issues:
  exclude-rules:
    - path: _test\.go|tests/.+\.go
      text: "(cyclomatic|cognitive)"  # false positives when using subtests
      linters:
        - revive
    - path: _test\.go|tests/.+\.go
      linters:
        - goerr113  # like err = errors.New("test error")
    - path: ^tools\/.+\.go
      linters:
        - goerr113
        - revive
